package lk.ijse.BackeryManagement.util;

public enum Routes {
 SIGNUPFORM,DASHBOARDFORM,EMPLOYEEFORM,PRODUCTFORM,VEHICLEFORM,MATERIALSTOCKFORM,PAYMENTFORM,PAYROLLFORM,ATTENDANCEFORM,MATERIALUSAGEFORM ,DELIVERYDETAILSFORM,REPORTSFORM,SUMMARYFORM
}
